dashboardSidebar(width = 230,
                 sidebarMenu(
                   id = 'tabs',
                   color = 'olive',
                   menuItem('Welcome',
                            tabName = 'welcome',
                            icon = icon('bullhorn')),
                   menuItem('常用小工具',
                            tabName = 'useful_tools',
                            icon = icon('list'),
                            menuSubItem('异常值/正态性/方差齐性',
                                        tabName = 'outliers_detect',
                                        icon = icon('search')),
                            menuSubItem('分组求和/均值/标准差(误)',
                                        tabName = 'mean_etal_by_group',
                                        icon = icon('ruler-vertical'))),
                   menuItem('统计&分析',
                            icon = icon('list'),
                            menuSubItem('t检验',
                                        tabName = 't_test', 
                                        icon = icon('paper-plane')),
                            menuSubItem('PCA',
                                        tabName = 'pca',
                                        icon = icon('paper-plane')),
                            menuSubItem('RDA',
                                        tabName = 'rda',
                                        icon = icon('paper-plane')),
                            menuSubItem('PCoA',
                                        tabName = 'pcoa',
                                        icon = icon('paper-plane')),
                            menuSubItem('NMDS',
                                        tabName = 'nmds',
                                        icon = icon('paper-plane')),
                            menuSubItem('PLS-DA',
                                        tabName = 'plsda',
                                        icon = icon('paper-plane')),
                            menuSubItem('OPLS-DA',
                                        tabName = 'oplsda',
                                        icon = icon('paper-plane')),
                            menuSubItem('方差分析',
                                        tabName = 'anova',
                                        icon = icon('paper-plane')),
                            menuSubItem('回归分析',
                                        tabName = 'regression',
                                        icon = icon('paper-plane')),
                            menuSubItem('相关分析',
                                        tabName = 'cor_test',
                                        icon = icon('paper-plane')),
                            menuSubItem('随机森林',
                                        tabName = 'random_forest',
                                        icon = icon('tree')),
                            menuSubItem('Wilcox检验',
                                        tabName = 'wilcox',
                                        icon = icon('paper-plane')),
                            menuSubItem('Kruskal检验',
                                        tabName = 'kruskal',
                                        icon = icon('paper-plane')),
                            menuSubItem('PERMANOVA',
                                        tabName = 'permanova',
                                        icon = icon('paper-plane'))),
                   menuItem('数据可视化',
                            icon = icon('list'),
                            menuSubItem('热力图',
                                        tabName = 'heatmap',
                                        icon = icon('chess-board')),
                            menuSubItem('散点图',
                                        tabName = 'point_plot', 
                                        icon = icon('ellipsis-v')),
                            menuSubItem('折线图',
                                        tabName = 'line_plot',
                                        icon = icon('water')),
                            menuSubItem('回归图',
                                        tabName = 'regression_plot',
                                        icon = icon('chart-line')),
                            menuSubItem('箱线图',
                                        tabName = 'box_plot',
                                        icon = icon('boxes')),
                            menuSubItem('火山图',
                                        tabName = 'volcanic_plot',
                                        icon = icon('drafting-compass')),
                            menuSubItem('韦恩图',
                                        tabName = 'venn_plot',
                                        icon = icon('drafting-compass')),
                            menuSubItem('坡度图',
                                        tabName = 'slope_plot',
                                        icon = icon('drafting-compass')),
                            menuSubItem('词云图',
                                        tabName = 'word_plot',
                                        icon = icon('cloud')),
                            menuSubItem('桑基图',
                                        tabName = 'sankey_plot',
                                        icon = icon('confluence')),
                            menuSubItem('小提琴图',
                                        tabName = 'violin_plot',
                                        icon = icon('drafting-compass')),
                            menuSubItem('圆堆积图',
                                        tabName = 'circle_stack_plot',
                                        icon = icon('circle-notch')),
                            menuSubItem('相关性图',
                                        tabName = 'cor_plot',
                                        icon = icon('check-double')),
                            menuSubItem('棒棒糖图',
                                        tabName = 'lollipop_plot',
                                        icon = icon('bone')),
                            menuSubItem('简单柱状图',
                                        tabName = 'simple_bar',
                                        icon = icon('chart-bar')),
                            menuSubItem('堆积柱状图',
                                        tabName = 'stacked_bar',
                                        icon = icon('database')),
                            menuSubItem('百分比柱状图',
                                        tabName = 'percent_bar',
                                        icon = icon('chart-bar'))
                            
                   )))